//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Static_View.Ctrip {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", ConfigurationName="Ctrip.AutoMappingServicesSoap")]
    public interface AutoMappingServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetCtripSubHotelInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CtripSubHotelInfoRS")]
        MVC_Static_View.Ctrip.CtripSubHotelInfoRS GetCtripSubHotelInfo(string masterHotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetCtripSubHotelInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CtripSubHotelInfoRS")]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.CtripSubHotelInfoRS> GetCtripSubHotelInfoAsync(string masterHotelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetRoomProductInfoRS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RoomProductInfoRS")]
        MVC_Static_View.Ctrip.ProductMappingInfoRS GetRoomProductInfo(string subHotelId, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetRoomProductInfoRS", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RoomProductInfoRS")]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.ProductMappingInfoRS> GetRoomProductInfoAsync(string subHotelId, string type);
        
        // CODEGEN: 操作 SetMappingInfo 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#SetMappingInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVC_Static_View.Ctrip.SetMappingInfoResponse SetMappingInfo(MVC_Static_View.Ctrip.SetMappingInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#SetMappingInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.SetMappingInfoResponse> SetMappingInfoAsync(MVC_Static_View.Ctrip.SetMappingInfoRequest request);
        
        // CODEGEN: 操作 IntelligentMapping 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#IntelligentMapping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVC_Static_View.Ctrip.IntelligentMappingResponse IntelligentMapping(MVC_Static_View.Ctrip.IntelligentMappingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#IntelligentMapping", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.IntelligentMappingResponse> IntelligentMappingAsync(MVC_Static_View.Ctrip.IntelligentMappingRequest request);
        
        // CODEGEN: 操作 MappingStatusSearch 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#MappingStatusSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVC_Static_View.Ctrip.MappingStatusSearchResponse MappingStatusSearch(MVC_Static_View.Ctrip.MappingStatusSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#MappingStatusSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.MappingStatusSearchResponse> MappingStatusSearchAsync(MVC_Static_View.Ctrip.MappingStatusSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetCtripSubHotelInfoByEBK" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CtripSubHotelInfoByEBKRS")]
        MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRS GetCtripSubHotelInfoByEBK(MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRQ CtripSubHotelInfoByEBKRQ);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://htng.org/2014B/HTNG_ARIAndReservationPushService#GetCtripSubHotelInfoByEBK" +
            "", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CtripSubHotelInfoByEBKRS")]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRS> GetCtripSubHotelInfoByEBKAsync(MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRQ CtripSubHotelInfoByEBKRQ);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class CtripSubHotelInfoRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string errorMsgField;
        
        private HotelInfo[] hotelInfosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public HotelInfo[] HotelInfos {
            get {
                return this.hotelInfosField;
            }
            set {
                this.hotelInfosField = value;
                this.RaisePropertyChanged("HotelInfos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class HotelInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subHotelIdField;
        
        private string masterHotelIdField;
        
        private string hotelNameField;
        
        private string addressField;
        
        private string provinceNameField;
        
        private string cityNameField;
        
        private string hotelBelongtoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string subHotelId {
            get {
                return this.subHotelIdField;
            }
            set {
                this.subHotelIdField = value;
                this.RaisePropertyChanged("subHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string masterHotelId {
            get {
                return this.masterHotelIdField;
            }
            set {
                this.masterHotelIdField = value;
                this.RaisePropertyChanged("masterHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
                this.RaisePropertyChanged("hotelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string provinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
                this.RaisePropertyChanged("provinceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string hotelBelongto {
            get {
                return this.hotelBelongtoField;
            }
            set {
                this.hotelBelongtoField = value;
                this.RaisePropertyChanged("hotelBelongto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class CtripSubHotelInfoByEBKRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string errorMsgField;
        
        private string hotelPropertyField;
        
        private HotelInfo[] hotelInfosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string hotelProperty {
            get {
                return this.hotelPropertyField;
            }
            set {
                this.hotelPropertyField = value;
                this.RaisePropertyChanged("hotelProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public HotelInfo[] HotelInfos {
            get {
                return this.hotelInfosField;
            }
            set {
                this.hotelInfosField = value;
                this.RaisePropertyChanged("HotelInfos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class CtripSubHotelInfoByEBKRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hotelCodeField;
        
        private string masterHotelIdField;
        
        private string subHotelIdField;
        
        private int hotelStatusField;
        
        private string reMarkField;
        
        private productSearchResult[] productSearchResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string hotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("hotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string masterHotelId {
            get {
                return this.masterHotelIdField;
            }
            set {
                this.masterHotelIdField = value;
                this.RaisePropertyChanged("masterHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subHotelId {
            get {
                return this.subHotelIdField;
            }
            set {
                this.subHotelIdField = value;
                this.RaisePropertyChanged("subHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int hotelStatus {
            get {
                return this.hotelStatusField;
            }
            set {
                this.hotelStatusField = value;
                this.RaisePropertyChanged("hotelStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string reMark {
            get {
                return this.reMarkField;
            }
            set {
                this.reMarkField = value;
                this.RaisePropertyChanged("reMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public productSearchResult[] productSearchResults {
            get {
                return this.productSearchResultsField;
            }
            set {
                this.productSearchResultsField = value;
                this.RaisePropertyChanged("productSearchResults");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class productSearchResult : SearchProductInfo {
        
        private string subRoomIdField;
        
        private int resultCodeField;
        
        private string resultMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string subRoomId {
            get {
                return this.subRoomIdField;
            }
            set {
                this.subRoomIdField = value;
                this.RaisePropertyChanged("subRoomId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(productSearchResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class SearchProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string roomTypeCodeField;
        
        private string ratePlanCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string roomTypeCode {
            get {
                return this.roomTypeCodeField;
            }
            set {
                this.roomTypeCodeField = value;
                this.RaisePropertyChanged("roomTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ratePlanCode {
            get {
                return this.ratePlanCodeField;
            }
            set {
                this.ratePlanCodeField = value;
                this.RaisePropertyChanged("ratePlanCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class MappingStatusSearchRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        private data[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public data[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("list");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class MappingStatusSearchRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hotelCodeField;
        
        private string subHotelIdField;
        
        private SearchProductInfo[] searchProductInfosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string hotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("hotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string subHotelId {
            get {
                return this.subHotelIdField;
            }
            set {
                this.subHotelIdField = value;
                this.RaisePropertyChanged("subHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public SearchProductInfo[] searchProductInfos {
            get {
                return this.searchProductInfosField;
            }
            set {
                this.searchProductInfosField = value;
                this.RaisePropertyChanged("searchProductInfos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class Match : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string otaRoomIdField;
        
        private string scoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string otaRoomId {
            get {
                return this.otaRoomIdField;
            }
            set {
                this.otaRoomIdField = value;
                this.RaisePropertyChanged("otaRoomId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("score");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RoomMatchRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string retCodeField;
        
        private string msgField;
        
        private Match[] matchResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Match[] matchResults {
            get {
                return this.matchResultsField;
            }
            set {
                this.matchResultsField = value;
                this.RaisePropertyChanged("matchResults");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class otaProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ota_RoomIdField;
        
        private string ota_RoomNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ota_RoomId {
            get {
                return this.ota_RoomIdField;
            }
            set {
                this.ota_RoomIdField = value;
                this.RaisePropertyChanged("ota_RoomId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ota_RoomName {
            get {
                return this.ota_RoomNameField;
            }
            set {
                this.ota_RoomNameField = value;
                this.RaisePropertyChanged("ota_RoomName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RoomMatchRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string roomTypeCodeField;
        
        private string roomTypeNameField;
        
        private string ratePlanNameField;
        
        private otaProductInfo[] otaProductListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string roomTypeCode {
            get {
                return this.roomTypeCodeField;
            }
            set {
                this.roomTypeCodeField = value;
                this.RaisePropertyChanged("roomTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string roomTypeName {
            get {
                return this.roomTypeNameField;
            }
            set {
                this.roomTypeNameField = value;
                this.RaisePropertyChanged("roomTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ratePlanName {
            get {
                return this.ratePlanNameField;
            }
            set {
                this.ratePlanNameField = value;
                this.RaisePropertyChanged("ratePlanName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public otaProductInfo[] otaProductList {
            get {
                return this.otaProductListField;
            }
            set {
                this.otaProductListField = value;
                this.RaisePropertyChanged("otaProductList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class SetMappingRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class SetMappingRQ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hotelCodeField;
        
        private string roomTypeCodeField;
        
        private string ratePlanCodeField;
        
        private string subHotelIdField;
        
        private string masterHotelIdField;
        
        private string subRoomIdField;
        
        private int setTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string hotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
                this.RaisePropertyChanged("hotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string roomTypeCode {
            get {
                return this.roomTypeCodeField;
            }
            set {
                this.roomTypeCodeField = value;
                this.RaisePropertyChanged("roomTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ratePlanCode {
            get {
                return this.ratePlanCodeField;
            }
            set {
                this.ratePlanCodeField = value;
                this.RaisePropertyChanged("ratePlanCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string subHotelId {
            get {
                return this.subHotelIdField;
            }
            set {
                this.subHotelIdField = value;
                this.RaisePropertyChanged("subHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string masterHotelId {
            get {
                return this.masterHotelIdField;
            }
            set {
                this.masterHotelIdField = value;
                this.RaisePropertyChanged("masterHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string subRoomId {
            get {
                return this.subRoomIdField;
            }
            set {
                this.subRoomIdField = value;
                this.RaisePropertyChanged("subRoomId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int setType {
            get {
                return this.setTypeField;
            }
            set {
                this.setTypeField = value;
                this.RaisePropertyChanged("setType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class RoomProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subHotelIdField;
        
        private string masterRoomIdField;
        
        private string subRoomIdField;
        
        private string breakfastField;
        
        private string balanceTypeField;
        
        private string subRoomNameField;
        
        private string pmsRoomTypeCodeField;
        
        private string pmsRoomNameField;
        
        private string pmsHotelCodeField;
        
        private string pmsRatePlanCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string subHotelId {
            get {
                return this.subHotelIdField;
            }
            set {
                this.subHotelIdField = value;
                this.RaisePropertyChanged("subHotelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string masterRoomId {
            get {
                return this.masterRoomIdField;
            }
            set {
                this.masterRoomIdField = value;
                this.RaisePropertyChanged("masterRoomId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subRoomId {
            get {
                return this.subRoomIdField;
            }
            set {
                this.subRoomIdField = value;
                this.RaisePropertyChanged("subRoomId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string breakfast {
            get {
                return this.breakfastField;
            }
            set {
                this.breakfastField = value;
                this.RaisePropertyChanged("breakfast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string balanceType {
            get {
                return this.balanceTypeField;
            }
            set {
                this.balanceTypeField = value;
                this.RaisePropertyChanged("balanceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string subRoomName {
            get {
                return this.subRoomNameField;
            }
            set {
                this.subRoomNameField = value;
                this.RaisePropertyChanged("subRoomName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string pmsRoomTypeCode {
            get {
                return this.pmsRoomTypeCodeField;
            }
            set {
                this.pmsRoomTypeCodeField = value;
                this.RaisePropertyChanged("pmsRoomTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string pmsRoomName {
            get {
                return this.pmsRoomNameField;
            }
            set {
                this.pmsRoomNameField = value;
                this.RaisePropertyChanged("pmsRoomName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string pmsHotelCode {
            get {
                return this.pmsHotelCodeField;
            }
            set {
                this.pmsHotelCodeField = value;
                this.RaisePropertyChanged("pmsHotelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string pmsRatePlanCode {
            get {
                return this.pmsRatePlanCodeField;
            }
            set {
                this.pmsRatePlanCodeField = value;
                this.RaisePropertyChanged("pmsRatePlanCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.opentravel.org/OTA/2003/05")]
    public partial class ProductMappingInfoRS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int retCodeField;
        
        private string errorMsgField;
        
        private RoomProductInfo[] roomProductInfosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int retCode {
            get {
                return this.retCodeField;
            }
            set {
                this.retCodeField = value;
                this.RaisePropertyChanged("retCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public RoomProductInfo[] RoomProductInfos {
            get {
                return this.roomProductInfosField;
            }
            set {
                this.roomProductInfosField = value;
                this.RaisePropertyChanged("RoomProductInfos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMappingInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public MVC_Static_View.Ctrip.SetMappingRQ SetMappingRQ;
        
        public SetMappingInfoRequest() {
        }
        
        public SetMappingInfoRequest(MVC_Static_View.Ctrip.SetMappingRQ SetMappingRQ) {
            this.SetMappingRQ = SetMappingRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetMappingInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public MVC_Static_View.Ctrip.SetMappingRS SetMappingRS;
        
        public SetMappingInfoResponse() {
        }
        
        public SetMappingInfoResponse(MVC_Static_View.Ctrip.SetMappingRS SetMappingRS) {
            this.SetMappingRS = SetMappingRS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntelligentMappingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public MVC_Static_View.Ctrip.RoomMatchRQ IntelligentMappingRQ;
        
        public IntelligentMappingRequest() {
        }
        
        public IntelligentMappingRequest(MVC_Static_View.Ctrip.RoomMatchRQ IntelligentMappingRQ) {
            this.IntelligentMappingRQ = IntelligentMappingRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IntelligentMappingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public MVC_Static_View.Ctrip.RoomMatchRS IntelligentMappingRS;
        
        public IntelligentMappingResponse() {
        }
        
        public IntelligentMappingResponse(MVC_Static_View.Ctrip.RoomMatchRS IntelligentMappingRS) {
            this.IntelligentMappingRS = IntelligentMappingRS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MappingStatusSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public MVC_Static_View.Ctrip.MappingStatusSearchRQ MappingStatusSearchRQ;
        
        public MappingStatusSearchRequest() {
        }
        
        public MappingStatusSearchRequest(MVC_Static_View.Ctrip.MappingStatusSearchRQ MappingStatusSearchRQ) {
            this.MappingStatusSearchRQ = MappingStatusSearchRQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MappingStatusSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opentravel.org/OTA/2003/05", Order=0)]
        public MVC_Static_View.Ctrip.MappingStatusSearchRS MappingStatusSearchRS;
        
        public MappingStatusSearchResponse() {
        }
        
        public MappingStatusSearchResponse(MVC_Static_View.Ctrip.MappingStatusSearchRS MappingStatusSearchRS) {
            this.MappingStatusSearchRS = MappingStatusSearchRS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoMappingServicesSoapChannel : MVC_Static_View.Ctrip.AutoMappingServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoMappingServicesSoapClient : System.ServiceModel.ClientBase<MVC_Static_View.Ctrip.AutoMappingServicesSoap>, MVC_Static_View.Ctrip.AutoMappingServicesSoap {
        
        public AutoMappingServicesSoapClient() {
        }
        
        public AutoMappingServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoMappingServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoMappingServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoMappingServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Static_View.Ctrip.CtripSubHotelInfoRS GetCtripSubHotelInfo(string masterHotelId) {
            return base.Channel.GetCtripSubHotelInfo(masterHotelId);
        }
        
        public System.Threading.Tasks.Task<MVC_Static_View.Ctrip.CtripSubHotelInfoRS> GetCtripSubHotelInfoAsync(string masterHotelId) {
            return base.Channel.GetCtripSubHotelInfoAsync(masterHotelId);
        }
        
        public MVC_Static_View.Ctrip.ProductMappingInfoRS GetRoomProductInfo(string subHotelId, string type) {
            return base.Channel.GetRoomProductInfo(subHotelId, type);
        }
        
        public System.Threading.Tasks.Task<MVC_Static_View.Ctrip.ProductMappingInfoRS> GetRoomProductInfoAsync(string subHotelId, string type) {
            return base.Channel.GetRoomProductInfoAsync(subHotelId, type);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_Static_View.Ctrip.SetMappingInfoResponse MVC_Static_View.Ctrip.AutoMappingServicesSoap.SetMappingInfo(MVC_Static_View.Ctrip.SetMappingInfoRequest request) {
            return base.Channel.SetMappingInfo(request);
        }
        
        public MVC_Static_View.Ctrip.SetMappingRS SetMappingInfo(MVC_Static_View.Ctrip.SetMappingRQ SetMappingRQ) {
            MVC_Static_View.Ctrip.SetMappingInfoRequest inValue = new MVC_Static_View.Ctrip.SetMappingInfoRequest();
            inValue.SetMappingRQ = SetMappingRQ;
            MVC_Static_View.Ctrip.SetMappingInfoResponse retVal = ((MVC_Static_View.Ctrip.AutoMappingServicesSoap)(this)).SetMappingInfo(inValue);
            return retVal.SetMappingRS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.SetMappingInfoResponse> MVC_Static_View.Ctrip.AutoMappingServicesSoap.SetMappingInfoAsync(MVC_Static_View.Ctrip.SetMappingInfoRequest request) {
            return base.Channel.SetMappingInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC_Static_View.Ctrip.SetMappingInfoResponse> SetMappingInfoAsync(MVC_Static_View.Ctrip.SetMappingRQ SetMappingRQ) {
            MVC_Static_View.Ctrip.SetMappingInfoRequest inValue = new MVC_Static_View.Ctrip.SetMappingInfoRequest();
            inValue.SetMappingRQ = SetMappingRQ;
            return ((MVC_Static_View.Ctrip.AutoMappingServicesSoap)(this)).SetMappingInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_Static_View.Ctrip.IntelligentMappingResponse MVC_Static_View.Ctrip.AutoMappingServicesSoap.IntelligentMapping(MVC_Static_View.Ctrip.IntelligentMappingRequest request) {
            return base.Channel.IntelligentMapping(request);
        }
        
        public MVC_Static_View.Ctrip.RoomMatchRS IntelligentMapping(MVC_Static_View.Ctrip.RoomMatchRQ IntelligentMappingRQ) {
            MVC_Static_View.Ctrip.IntelligentMappingRequest inValue = new MVC_Static_View.Ctrip.IntelligentMappingRequest();
            inValue.IntelligentMappingRQ = IntelligentMappingRQ;
            MVC_Static_View.Ctrip.IntelligentMappingResponse retVal = ((MVC_Static_View.Ctrip.AutoMappingServicesSoap)(this)).IntelligentMapping(inValue);
            return retVal.IntelligentMappingRS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.IntelligentMappingResponse> MVC_Static_View.Ctrip.AutoMappingServicesSoap.IntelligentMappingAsync(MVC_Static_View.Ctrip.IntelligentMappingRequest request) {
            return base.Channel.IntelligentMappingAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC_Static_View.Ctrip.IntelligentMappingResponse> IntelligentMappingAsync(MVC_Static_View.Ctrip.RoomMatchRQ IntelligentMappingRQ) {
            MVC_Static_View.Ctrip.IntelligentMappingRequest inValue = new MVC_Static_View.Ctrip.IntelligentMappingRequest();
            inValue.IntelligentMappingRQ = IntelligentMappingRQ;
            return ((MVC_Static_View.Ctrip.AutoMappingServicesSoap)(this)).IntelligentMappingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_Static_View.Ctrip.MappingStatusSearchResponse MVC_Static_View.Ctrip.AutoMappingServicesSoap.MappingStatusSearch(MVC_Static_View.Ctrip.MappingStatusSearchRequest request) {
            return base.Channel.MappingStatusSearch(request);
        }
        
        public MVC_Static_View.Ctrip.MappingStatusSearchRS MappingStatusSearch(MVC_Static_View.Ctrip.MappingStatusSearchRQ MappingStatusSearchRQ) {
            MVC_Static_View.Ctrip.MappingStatusSearchRequest inValue = new MVC_Static_View.Ctrip.MappingStatusSearchRequest();
            inValue.MappingStatusSearchRQ = MappingStatusSearchRQ;
            MVC_Static_View.Ctrip.MappingStatusSearchResponse retVal = ((MVC_Static_View.Ctrip.AutoMappingServicesSoap)(this)).MappingStatusSearch(inValue);
            return retVal.MappingStatusSearchRS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC_Static_View.Ctrip.MappingStatusSearchResponse> MVC_Static_View.Ctrip.AutoMappingServicesSoap.MappingStatusSearchAsync(MVC_Static_View.Ctrip.MappingStatusSearchRequest request) {
            return base.Channel.MappingStatusSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC_Static_View.Ctrip.MappingStatusSearchResponse> MappingStatusSearchAsync(MVC_Static_View.Ctrip.MappingStatusSearchRQ MappingStatusSearchRQ) {
            MVC_Static_View.Ctrip.MappingStatusSearchRequest inValue = new MVC_Static_View.Ctrip.MappingStatusSearchRequest();
            inValue.MappingStatusSearchRQ = MappingStatusSearchRQ;
            return ((MVC_Static_View.Ctrip.AutoMappingServicesSoap)(this)).MappingStatusSearchAsync(inValue);
        }
        
        public MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRS GetCtripSubHotelInfoByEBK(MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRQ CtripSubHotelInfoByEBKRQ) {
            return base.Channel.GetCtripSubHotelInfoByEBK(CtripSubHotelInfoByEBKRQ);
        }
        
        public System.Threading.Tasks.Task<MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRS> GetCtripSubHotelInfoByEBKAsync(MVC_Static_View.Ctrip.CtripSubHotelInfoByEBKRQ CtripSubHotelInfoByEBKRQ) {
            return base.Channel.GetCtripSubHotelInfoByEBKAsync(CtripSubHotelInfoByEBKRQ);
        }
    }
}
